name: BXTpa
version: '${version}'
main: top.craft_hello.tpa.TPA
description: Spigot ve Paper sunucuları için tamamen Türkçe TPA eklentisi
author: Furkan Studio
folia-supported: true

commands:
  tpa:
    description: Bir oyuncuya ışınlanma isteği gönderir
    usage: /tpa <oyuncu>
  tphere:
    description: Bir oyuncunun senin yanına ışınlanmasını ister
    usage: /tphere <oyuncu>
  tpaccept:
    description: Gelen ışınlanma isteğini kabul eder
    usage: /tpaccept
  tpdeny:
    description: Gelen ışınlanma isteğini reddeder
    usage: /tpdeny

permissions:
  bxtpa.tpa:
    default: true
    description: /tpa komutunu kullanabilir
  bxtpa.tphere:
    default: true
    description: /tphere komutunu kullanabilir
